= A XML Processing Family

Generated by https://starter-toolkit.talend.io/.

Run `./mvnw clean install` to build the project.
Run `./mvnw talend-component:web` to run the web UI.
Run `./mvnw talend-component:deploy-in-studio -Dtalend.component.studioHome=/path/to/studio` to deploy in a studio instance.

== Runtime

=== Apache Beam

Beam facet generates component tests using Apache Beam testing framework. It executes the tests using a real beam pipeline to go through the runtime constraints of Apache Beam which can be more strict than Talend Component Kit ones.

==== Files generated by this facet

- src/test/java/org/talend/components/xml/processing/processor/CompanyComponent1ProcessorBeamTest.java
- src/test/java/org/talend/components/xml/processing/processor/XSDValidatorProcessorBeamTest.java
- src/test/java/org/talend/components/xml/processing/processor/XSLTTransformerProcessorBeamTest.java


== Test

=== Talend Component Kit Testing

Talend Component Kit Testing skeleton generator. For each component selected it generates an associated test suffixed with `Test`.

==== Files generated by this facet

- src/test/java/org/talend/components/xml/processing/processor/CompanyComponent1ProcessorTest.java
- src/test/java/org/talend/components/xml/processing/processor/XSDValidatorProcessorTest.java
- src/test/java/org/talend/components/xml/processing/processor/XSLTTransformerProcessorTest.java


